In [62]:
###THIS SOLUTION GETS 10s IN ALL PROBLEMS
##########################################
from collections import namedtuple
import numpy as np
from operator import itemgetter
import time
from bitarray import bitarray

input_location = './data/ks_4_0'
with open(input_location, 'r') as input_data_file:
    input_data = input_data_file.read()
print(input_data)

Item = namedtuple("Item", ['index', 'value', 'weight'])

# parse the input
lines = input_data.split('\n')

firstLine = lines[0].split()
item_count = int(firstLine[0])
capacity = int(firstLine[1])

items = []

for i in range(1, item_count + 1):
    line = lines[i]
    parts = line.split()
    items.append(Item(i - 1, int(parts[0]), int(parts[1])))

init_time = time.time()

items.sort(reverse=True, key=itemgetter(2))

print(items)

origin_row = np.zeros((capacity+1,1), dtype=np.int32)
destination_row = np.zeros((capacity+1,1), dtype=np.int32)

back_tracing = np.matrix(np.zeros((capacity+1, item_count+1), dtype=bool))
testMatrix = np.matrix(np.zeros((capacity+1, item_count+1), dtype=int))

for j in range(1, item_count+1):
    destination_row[items[j-1][2]:] = np.maximum(origin_row[:][items[j-1][2]:], (np.roll(origin_row[:],items[j-1][2],axis=0)[items[j-1][2]:] + items[j-1][1]))
    back_tracing[:,j] = destination_row[:]==origin_row[:]
    origin_row[:] = destination_row[:]
    testMatrix[:,j] = destination_row[:]

print(testMatrix)
# print(back_tracing)
###backtracing

pointer = (capacity, item_count)
taken = [0]*len(items)
for i in range(item_count-1,-1,-1):
    if back_tracing[pointer]==True:
        pointer = (pointer[0],pointer[1]-1)
    else:
        pointer = (pointer[0]-items[pointer[1]-1][2],pointer[1]-1)
        taken[i] = 1
end_time = time.time()

indexes = [it[0] for it in items]
taken = [i for _,i in sorted(zip(indexes, taken))]


value = destination_row[-1][0]

# prepare the solution in the specified output format
output_data = str(value) + ' ' + str(1) + '\n'
output_data += ' '.join(map(str, taken))

print(output_data)


4 11
8 4
10 5
15 8
4 3

[Item(index=2, value=15, weight=8), Item(index=1, value=10, weight=5), Item(index=0, value=8, weight=4), Item(index=3, value=4, weight=3)]
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  4]
 [ 0  0  0  8  8]
 [ 0  0 10 10 10]
 [ 0  0 10 10 10]
 [ 0  0 10 10 12]
 [ 0 15 15 15 15]
 [ 0 15 15 18 18]
 [ 0 15 15 18 18]
 [ 0 15 15 18 19]]
19 1
0 0 1 1


In [57]:
###THIS SOLUTION FAILS IN PROBLEMS 4 AND 6, AND GETS 10 IN OTHERS
#################################

import operator
from collections import namedtuple
import numpy as np
from operator import itemgetter
import time

input_location = './data/ks_100_0'
with open(input_location, 'r') as input_data_file:
    input_data = input_data_file.read()
print(input_data)

Item = namedtuple("Item", ['index', 'value', 'weight'])

# parse the input
lines = input_data.split('\n')

firstLine = lines[0].split()
item_count = int(firstLine[0])
capacity = int(firstLine[1])

items = []

for i in range(1, item_count + 1):
    line = lines[i]
    parts = line.split()
    items.append(Item(i - 1, int(parts[0]), int(parts[1])))

init_time = time.time()

items.sort(reverse=True, key=itemgetter(2))

print(items)


dp_table = np.matrix(np.zeros((capacity+1, item_count+1), dtype=np.int32))
print(dp_table)


#filling dynamic programming table
for j in range(1, item_count+1):
    dp_table[items[j-1][2]:, j] = np.maximum(dp_table[items[j-1][2]:, j-1], (np.roll(dp_table[:,j-1],items[j-1][2],axis=0)[items[j-1][2]:] + items[j-1][1]))

end_time = time.time()


print(dp_table)
print('dp table time: {}'.format(end_time-init_time))

init_time = time.time()
##traceBack
pointer = (capacity, item_count)
taken = [0]*len(items)
for i in range(item_count-1,-1,-1):
    if dp_table[pointer]==dp_table[pointer[0],pointer[1]-1]:
        pointer = (pointer[0],pointer[1]-1)
    else:
        pointer = (pointer[0]-items[pointer[1]-1][2],pointer[1]-1)
        taken[i] = 1
end_time = time.time()
print('dp traceback time: {}'.format(end_time-init_time))

indexes = [it[0] for it in items]
taken = [i for _,i in sorted(zip(indexes, taken))]


value = dp_table[capacity, item_count]

# prepare the solution in the specified output format
output_data = str(value) + ' ' + str(1) + '\n'
output_data += ' '.join(map(str, taken))

print(output_data)


100 100000
90000 90001
89750 89751
10001 10002
89500 89501
10252 10254
89250 89251
10503 10506
89000 89001
10754 10758
88750 88751
11005 11010
88500 88501
11256 11262
88250 88251
11507 11514
88000 88001
11758 11766
87750 87751
12009 12018
87500 87501
12260 12270
87250 87251
12511 12522
87000 87001
12762 12774
86750 86751
13013 13026
86500 86501
13264 13278
86250 86251
13515 13530
86000 86001
13766 13782
85750 85751
14017 14034
85500 85501
14268 14286
85250 85251
14519 14538
85000 85001
14770 14790
84750 84751
15021 15042
84500 84501
15272 15294
84250 84251
15523 15546
84000 84001
15774 15798
83750 83751
16025 16050
83500 83501
16276 16302
83250 83251
16527 16554
83000 83001
16778 16806
82750 82751
17029 17058
82500 82501
17280 17310
82250 82251
17531 17562
82000 82001
17782 17814
81750 81751
18033 18066
81500 81501
18284 18318
81250 81251
18535 18570
81000 81001
18786 18822
80750 80751
19037 19074
80500 80501
19288 19326
80250 80251
19539 19578
80000 80001
19790 19830
79750 79751
20041

In [54]:
init_time = time.time()

print(items)


dp_table = np.zeros((capacity+1, item_count+1))
print(dp_table)


#filling dynamic programming table
for j in range(1, item_count+1):
    for i in range(capacity+1):
        if items[j-1][2] <= i:
            dp_table[i, j] = np.maximum(dp_table[i, j-1], dp_table[i - items[j-1][2], j-1] + items[j-1][1])
        else:
            dp_table[i, j] = dp_table[i, j-1]

end_time = time.time()


#############################

init_time = time.time()

items.sort(reverse=True, key=itemgetter(2))

print(items)


dp_table = np.zeros((capacity+1, item_count+1))
print(dp_table)


#filling dynamic programming table
for j in range(1, item_count+1):
    for i in range(items[j-1][2], capacity+1):
        dp_table[i, j] = np.maximum(dp_table[i, j-1], dp_table[i - items[j-1][2], j-1] + items[j-1][1])

end_time = time.time()



11.0


In [25]:
A = np.array([[1,2],[5,3],[8,9]])
B = A[:,1]
C = A[:,0]
print(np.roll(B,2,axis=0))

D = np.maximum(B,C)
print(D)



[3 9 2]
[2 5 9]


In [2]:
import operator
from more_itertools import sort_together

list = [[0,2],[1,5],[2,1]]
list.sort(key=lambda elem: elem[1])
print(list)

indexes = [it[0] for it in items]

taken = [i for _,i in sorted(zip(indexes, taken))]

print(taken)


[[2, 1], [0, 2], [1, 5]]
[1, 0, 0]


In [ ]:


pointer = (capacity, item_count)
p = (1,1)
a = p[0] - 2
print(dp_table[pointer])

In [ ]:



from operator import itemgetter
it = items.sort(reverse=True, key=itemgetter(1))
print(items)

In [38]:
it = np.matrix(items)
print(it)

[[ 2 15  8]
 [ 1 10  5]
 [ 0  8  4]
 [ 3  4  3]]
